"""initial schema

Revision ID: d1dcd0daeaf9
Revises: 
Create Date: 2026-07-29 10:06:13.342307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1dcd0daeaf9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('year_group', sa.String(length=32), nullable=True),
    sa.Column('curriculum', sa.String(length=48), nullable=True),
    sa.Column('target_degree', sa.String(length=120), nullable=True),
    sa.Column('weekday_hours', sa.Float(), nullable=False),
    sa.Column('weekend_hours', sa.Float(), nullable=False),
    sa.Column('preferred_study_time', sa.String(length=24), nullable=False),
    sa.Column('study_habits', sa.Text(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('streak_current', sa.Integer(), nullable=False),
    sa.Column('streak_longest', sa.Integer(), nullable=False),
    sa.Column('last_study_date', sa.Date(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('onboarding_step', sa.Integer(), nullable=False),
    sa.Column('onboarding_draft', sa.Text(), nullable=True),
    sa.Column('mentor_summary', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=48), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_achievements_user_id'), ['user_id'], unique=False)

    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=False),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_user_id'), ['user_id'], unique=False)

    op.create_table('admission_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('preparation_percentage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admission_exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admission_exams_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('study_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.Text(), nullable=True),
    sa.Column('focus_notes', sa.Text(), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('regenerated_from_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_plans_user_id'), ['user_id'], unique=False)

    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('curriculum', sa.String(length=48), nullable=True),
    sa.Column('exam_board', sa.String(length=64), nullable=True),
    sa.Column('colour', sa.String(length=16), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=False),
    sa.Column('target_grade', sa.String(length=8), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('is_weak', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('syllabus_status', sa.String(length=20), nullable=False),
    sa.Column('syllabus_pdf_path', sa.String(length=255), nullable=True),
    sa.Column('syllabus_pdf_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_user_id'), ['user_id'], unique=False)

    op.create_table('target_universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('target_universities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_target_universities_user_id'), ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_reminders', sa.Boolean(), nullable=False),
    sa.Column('study_reminders', sa.Boolean(), nullable=False),
    sa.Column('weekly_report', sa.Boolean(), nullable=False),
    sa.Column('calendar_sync', sa.Boolean(), nullable=False),
    sa.Column('auto_reschedule', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_settings_user_id'), ['user_id'], unique=True)

    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('exam_board', sa.String(length=64), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('exam_time', sa.String(length=16), nullable=True),
    sa.Column('paper', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('preparation_percentage', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_exam_date'), ['exam_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_user_id'), ['user_id'], unique=False)

    op.create_table('past_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('exam_board', sa.String(length=64), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('paper', sa.String(length=64), nullable=True),
    sa.Column('session_label', sa.String(length=32), nullable=True),
    sa.Column('date_taken', sa.Date(), nullable=False),
    sa.Column('marks_scored', sa.Float(), nullable=False),
    sa.Column('marks_total', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=8), nullable=True),
    sa.Column('time_taken_minutes', sa.Integer(), nullable=True),
    sa.Column('under_timed_conditions', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('scored', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('past_papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_past_papers_date_taken'), ['date_taken'], unique=False)
        batch_op.create_index(batch_op.f('ix_past_papers_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_past_papers_user_id'), ['user_id'], unique=False)

    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_subject_id'), ['subject_id'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_unit_id'), ['unit_id'], unique=False)

    op.create_table('completed_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('completed_on', sa.Date(), nullable=False),
    sa.Column('minutes_spent', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('completed_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_completed_topics_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_completed_topics_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_completed_topics_user_id'), ['user_id'], unique=False)

    op.create_table('revision_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('interval_label', sa.String(length=16), nullable=False),
    sa.Column('repetition_index', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('recall_rating', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revision_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revision_plans_scheduled_date'), ['scheduled_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_revision_plans_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_revision_plans_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revision_plans_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revision_plans_user_id'), ['user_id'], unique=False)

    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=8), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('actual_minutes', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['study_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_sessions_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_sessions_session_date'), ['session_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_sessions_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_sessions_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_sessions_topic_id'))
        batch_op.drop_index(batch_op.f('ix_study_sessions_subject_id'))
        batch_op.drop_index(batch_op.f('ix_study_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_study_sessions_session_date'))
        batch_op.drop_index(batch_op.f('ix_study_sessions_plan_id'))

    op.drop_table('study_sessions')
    with op.batch_alter_table('revision_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revision_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_revision_plans_topic_id'))
        batch_op.drop_index(batch_op.f('ix_revision_plans_subject_id'))
        batch_op.drop_index(batch_op.f('ix_revision_plans_status'))
        batch_op.drop_index(batch_op.f('ix_revision_plans_scheduled_date'))

    op.drop_table('revision_plans')
    with op.batch_alter_table('completed_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_completed_topics_user_id'))
        batch_op.drop_index(batch_op.f('ix_completed_topics_topic_id'))
        batch_op.drop_index(batch_op.f('ix_completed_topics_subject_id'))

    op.drop_table('completed_topics')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_unit_id'))

    op.drop_table('topics')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_subject_id'))

    op.drop_table('units')
    with op.batch_alter_table('past_papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_past_papers_user_id'))
        batch_op.drop_index(batch_op.f('ix_past_papers_subject_id'))
        batch_op.drop_index(batch_op.f('ix_past_papers_date_taken'))

    op.drop_table('past_papers')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_user_id'))
        batch_op.drop_index(batch_op.f('ix_exams_subject_id'))
        batch_op.drop_index(batch_op.f('ix_exams_exam_date'))

    op.drop_table('exams')
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_user_id'))

    op.drop_table('user_settings')
    with op.batch_alter_table('target_universities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_target_universities_user_id'))

    op.drop_table('target_universities')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_user_id'))

    op.drop_table('subjects')
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_plans_user_id'))

    op.drop_table('study_plans')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    with op.batch_alter_table('admission_exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admission_exams_user_id'))

    op.drop_table('admission_exams')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_user_id'))

    op.drop_table('activity_logs')
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievements_user_id'))
        batch_op.drop_index(batch_op.f('ix_achievements_code'))

    op.drop_table('achievements')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
